T1=()
print(f"empty Tuple {T1}")
T2=(0,)
print(f"tuple with one element {T2}")
T3=(0,'hi',1.2,3)
print(f"tuple with three elements {T3}")
T4=0,'hi',1.2,3
print(f"tuple with three elements {T4}")
T5=("abc",('def','ghi'))
print(f"nested tuple {T5}")
T6=tuple('spam')
print(f"tuple with string {T6}")
print(T5[0])
print(T5[1][1])
print(T3[0:4])
print(len(T6))
